services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
      TZ: UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      -TZ: UTC
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db

  linter:
    build: .
    volumes:
      - .:/app
    entrypoint: [ "black", "." ]

  test:
    build: .
    command: pytest --cov=./ --cov-config=.coveragerc --cov-report=html
    environment:
      PYTHONPATH: .
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data:
